from __future__ import annotations

from .constants import (
    DEFAULT_REMOTE_CONTROL_BASE_URL,
    REMOTE_CONTROL_ACCOUNT_ID_HEADER,
    REMOTE_CONTROL_COMPAT_VERSION,
    REMOTE_CONTROL_INSTALLATION_ID_HEADER,
    REMOTE_CONTROL_PROTOCOL_VERSION,
    REMOTE_CONTROL_SERVER_NAME_ENV,
    REMOTE_CONTROL_SUBSCRIBE_CURSOR_HEADER,
    REMOTE_CONTROL_WEBSOCKET_CLIENT_PING_TIMEOUT_SECONDS,
    REMOTE_CONTROL_WEBSOCKET_PING_INTERVAL_SECONDS,
    REMOTE_CONTROL_WEBSOCKET_PONG_TIMEOUT_SECONDS,
    REQUIRED_REMOTE_CONTROL_SERVER_NAME,
)
from .types import (
    EnrollRemoteServerRequest,
    RemoteControlAuth,
    RemoteControlConfig,
    RemoteControlConnectionStatus,
    RemoteControlEnrollment,
    RemoteControlError,
    RemoteControlMode,
    RemoteControlReadyStatus,
    RemoteControlStartJsonOutput,
    RemoteControlTarget,
    RemoteControlUnavailable,
)
from .protocol import (
    ClientEnvelope,
    RemoteClientEvent,
    RemoteServerEvent,
    ServerEnvelope,
    _ClientSegmentReassembler,
    _OutboundBuffer,
    _split_server_envelope_for_transport,
)
from .local import (
    app_server_control_socket_available,
    app_server_control_socket_path,
    app_server_startup_lock_path,
)
from .transport import (
    _remote_auth_headers,
    _websocket_headers,
    build_enroll_request,
    enroll_remote_control_server,
    normalize_remote_control_url,
)
from .service import RemoteControlService
from .daemon import ensure_remote_control_daemon, run_native_remote_control, _read_daemon_ready_status
from .display import (
    remote_control_official_args,
    remote_control_start_human_lines,
    remote_control_start_json_output,
    remote_control_stop_human_message,
)
from .app_helpers import _last_user_message_index, _preview_from_history, _thread_item_from_response_item
from .app_server import _RemoteAppServer

__all__ = [
    "ClientEnvelope",
    "DEFAULT_REMOTE_CONTROL_BASE_URL",
    "EnrollRemoteServerRequest",
    "REMOTE_CONTROL_ACCOUNT_ID_HEADER",
    "REMOTE_CONTROL_COMPAT_VERSION",
    "REMOTE_CONTROL_INSTALLATION_ID_HEADER",
    "REMOTE_CONTROL_PROTOCOL_VERSION",
    "REMOTE_CONTROL_SERVER_NAME_ENV",
    "REMOTE_CONTROL_SUBSCRIBE_CURSOR_HEADER",
    "REMOTE_CONTROL_WEBSOCKET_CLIENT_PING_TIMEOUT_SECONDS",
    "REMOTE_CONTROL_WEBSOCKET_PING_INTERVAL_SECONDS",
    "REMOTE_CONTROL_WEBSOCKET_PONG_TIMEOUT_SECONDS",
    "REQUIRED_REMOTE_CONTROL_SERVER_NAME",
    "RemoteClientEvent",
    "RemoteControlError",
    "RemoteControlAuth",
    "RemoteControlConfig",
    "RemoteControlConnectionStatus",
    "RemoteControlEnrollment",
    "RemoteControlMode",
    "RemoteControlReadyStatus",
    "RemoteControlStartJsonOutput",
    "RemoteControlTarget",
    "RemoteControlService",
    "RemoteControlUnavailable",
    "RemoteServerEvent",
    "ServerEnvelope",
    "_ClientSegmentReassembler",
    "_OutboundBuffer",
    "_RemoteAppServer",
    "_last_user_message_index",
    "_preview_from_history",
    "_read_daemon_ready_status",
    "_remote_auth_headers",
    "_split_server_envelope_for_transport",
    "_thread_item_from_response_item",
    "_websocket_headers",
    "app_server_control_socket_available",
    "app_server_control_socket_path",
    "app_server_startup_lock_path",
    "build_enroll_request",
    "enroll_remote_control_server",
    "ensure_remote_control_daemon",
    "normalize_remote_control_url",
    "remote_control_official_args",
    "remote_control_start_human_lines",
    "remote_control_start_json_output",
    "remote_control_stop_human_message",
    "run_native_remote_control",
]
