from __future__ import annotations

import os
import socket

REMOTE_CONTROL_PROTOCOL_VERSION = "3"
REMOTE_CONTROL_ACCOUNT_ID_HEADER = "chatgpt-account-id"
REMOTE_CONTROL_INSTALLATION_ID_HEADER = "x-codex-installation-id"
REMOTE_CONTROL_SUBSCRIBE_CURSOR_HEADER = "x-codex-subscribe-cursor"
DEFAULT_REMOTE_CONTROL_BASE_URL = "https://chatgpt.com/backend-api"
REQUIRED_REMOTE_CONTROL_SERVER_NAME = (socket.gethostname() or "localhost").strip() or "localhost"
REMOTE_CONTROL_SERVER_NAME_ENV = "PY_CODEX_REMOTE_CONTROL_NAME"
REMOTE_CONTROL_COMPAT_VERSION = os.environ.get("PY_CODEX_REMOTE_CONTROL_VERSION", "0.133.0")
PYTHON_REMOTE_CONTROL_VERSION = REMOTE_CONTROL_COMPAT_VERSION
REMOTE_CONTROL_CONNECT_TIMEOUT_SECONDS = 30
REMOTE_CONTROL_RECONNECT_SECONDS = 5
REMOTE_CONTROL_WEBSOCKET_PING_INTERVAL_SECONDS = 10
REMOTE_CONTROL_WEBSOCKET_PONG_TIMEOUT_SECONDS = 60
REMOTE_CONTROL_WEBSOCKET_CLIENT_PING_TIMEOUT_SECONDS = REMOTE_CONTROL_WEBSOCKET_PONG_TIMEOUT_SECONDS
REMOTE_CONTROL_PID_FILE = "remote-control.pid"
REMOTE_CONTROL_STATE_FILE = "remote-control.json"
REMOTE_CONTROL_SEGMENT_TARGET_BYTES = 100 * 1024
REMOTE_CONTROL_SEGMENT_MAX_BYTES = 150 * 1024
REMOTE_CONTROL_REASSEMBLED_MAX_BYTES = 100 * 1024 * 1024
REMOTE_CONTROL_SEGMENT_COUNT_MAX = 1024
REMOTE_CONTROL_SEGMENT_ASSEMBLY_MAX_COUNT = 128
DEFAULT_REMOTE_PROCESS_OUTPUT_BYTES_CAP = 1024 * 1024
APP_SERVER_CONTROL_SOCKET_DIR_NAME = "app-server-control"
APP_SERVER_CONTROL_SOCKET_FILE_NAME = "app-server-control.sock"
APP_SERVER_STARTUP_LOCK_FILE_NAME = "app-server-startup.lock"
